# Generated by Django 4.1.3 on 2022-12-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='N͓̽a͓̽m͓̽e͓̽',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='քɦօռɛ',
            new_name='phone',
        ),
    ]
